sudo: required

services:
  - docker

env:
  global:
    - VLC_ANDROID_VERSION="3.2.11"
    - ARCHITECTURE=`echo "$TRAVIS_TAG" | sed -rn 's/^[^-]*-(.*)$/\1/p'`
    - DOCKER_CONTAINER_NAME="maximilize/vlc-android-sdk"

script:
  - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
  - while sleep 1m; do echo "[$SECONDS seconds] building libvlc for $ARCHITECTURE based on vlc-android $VLC_ANDROID_VERSION"; done &
  - docker build -t "$DOCKER_CONTAINER_NAME" . >/dev/null 2>/dev/null
  - docker run -it "$DOCKER_CONTAINER_NAME" "$VLC_ANDROID_VERSION" "$ARCHITECTURE" >/dev/null 2>/dev/null
  - kill %1
  - DOCKER_CONTAINER_ID=`docker ps -a | grep "$DOCKER_CONTAINER_NAME" | awk 'NR==1{ print $1 }'`
  - docker cp "$DOCKER_CONTAINER_ID:/home/ci/libvlc-$ARCHITECTURE-jni.zip" .

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ma1ybRz+XXYbLVZ545xLaZiDenw4TyrISfEUCHHUjEs9bGW7/L/7ii/g6iFT+26VicQJfwFRUOQSLy8Ng/4s8K/2u1Qm2y63xQUBBdRIsBM8PbelIQB75OWsWXIhdBbsB0sDSsv/74x7qujOUPShmHXjpM0mMkGCgacW0eV6mJUhVsnhpvRH6VXy9C38DD2hHtqHN9lvsM09pMAwPgskiIpM4fvkwEtU+v12d33G8SWAWbyV0FdWPpos+iXozYhDDpf2a0gMgdbK9LWUfsljb2KvukYnJmi8K3NEVWOwsw0gacEz3F+G/YIZ1o3bHStffWqOmuhScmS6XTRD3x6GQMsomguGNpkia4NlqiaLCEo7vMAmmRewcMiouZPHqMy3sIEWkrjxFn/KLQQ8jhUsm6G0u4sgXhZrEKTGB1P5IBt/Pf0B9J7KucAyk5V9cAic6AFDGxzkT+rfV/BEEQZ96BYg89UnBTYY4XjsvS8mpLIa0gC1twp6RpXsbhAxJJLyzi77eCQfPTm8FEqhA1qGLL1we0Vf2m8THOuI5QvNTsXn7tPD6sGHIfV/ECDuJlLQeFKPxHGfRWD2Q2dpsf5bwT2c8Q9gJGwa+ABaTr66iFbaF0dSMwr/0X6zoq8v6rh1eToTCsydBDvJsS3ATBFiApbOQ4ZJR4XGF0en3nBf8jU=
  file: "libvlc-$ARCHITECTURE-jni.zip"
  on:
    tags: true
    repo: maximilize/vlc-android-sdk
