#!/bin/bash
set -e

if [[ ! "$VLC_ANDROID_VERSION" =~ ^[0-9\.]+$ ]]
then
    echo "Invalid vlc android version: $VLC_ANDROID_VERSION"
    exit 1
fi

if [[ ! "$JNI_VERSION" =~ ^[0-9\.]+$ ]]
then
    echo "Skip building for vlc-android-sdk: $JNI_VERSION"
    exit 1
fi

PROJECT_DIR=`pwd`
ANDROID_NDK="$HOME"/ndk
rm -rf "$ANDROID_NDK"
mkdir -p "$ANDROID_NDK"
cd "$ANDROID_NDK"
wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
ANDROID_NDK_SHA1=500679655da3a86aecf67007e8ab230ea9b4dd7b
echo "$ANDROID_NDK_SHA1" android-ndk-r18b-linux-x86_64.zip | sha1sum -c
unzip android-ndk-r18b-linux-x86_64.zip
rm -f android-ndk-r18b-linux-x86_64.zip
mv android-ndk-r18b/** .
rm -rf android-ndk-r18b
cd "$PROJECT_DIR"
echo "ndk.dir=$ANDROID_NDK" > local.properties
echo "sdk.dir=$ANDROID_SDK" >> local.properties
wget https://services.gradle.org/distributions/gradle-4.6-bin.zip
GRADLE_SHA256=98bd5fd2b30e070517e03c51cbb32beee3e2ee1a84003a5a5d748996d4b1b915
echo "$GRADLE_SHA256" gradle-4.6-bin.zip | sha256sum -c
unzip gradle-4.6-bin.zip
rm -f gradle-4.6-bin.zip
cd gradle-4.6
./bin/gradle --offline wrapper
cd "$PROJECT_DIR"
mkdir gradle
mv gradle-4.6/gradle/wrapper/ gradle
mv gradle-4.6/gradlew .
chmod a+x gradlew
SRC_MAIN_DIR="src/main"
JNILIBS_DIR="$SRC_MAIN_DIR"/jniLibs
JAVA_DIR="$SRC_MAIN_DIR"/java
RES_DIR="$SRC_MAIN_DIR"/res
mkdir -p "$SRC_MAIN_DIR"
mkdir -p "$JNILIBS_DIR"
mkdir -p "$JAVA_DIR"
mkdir -p "$RES_DIR"
for ARCHITECTURE in armeabi-v7a arm64-v8a x86_64 x86
do
    wget https://github.com/maximilize/vlc-android-sdk/releases/download/"$JNI_VERSION"-"$ARCHITECTURE"/libvlc-"$ARCHITECTURE"-jni.zip
    unzip libvlc-"$ARCHITECTURE"-jni.zip
    rm -f libvlc-"$ARCHITECTURE"-jni.zip
    cp -r libvlc-jni/* "$JNILIBS_DIR"
    rm -rf libvlc-jni
done
git clone "https://code.videolan.org/videolan/vlc-android.git" -b "$VLC_ANDROID_VERSION" vlc-android
cp vlc-android/libvlc/AndroidManifest.xml "$SRC_MAIN_DIR"
cp -r vlc-android/libvlc/src/* "$JAVA_DIR/"
cp -r vlc-android/libvlc/res/* "$RES_DIR/"
rm -rf vlc-android
